# Generated by Django 3.2.7 on 2021-09-08 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_project_allocated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allocated_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
