# Generated by Django 3.2.7 on 2021-09-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_auto_20210924_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_marks',
            field=models.IntegerField(default=0, help_text='Enter passing percentage', max_length=100),
        ),
    ]
