# Generated by Django 3.2.7 on 2021-09-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_auto_20210909_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='total_attampts',
            new_name='total_attempts',
        ),
    ]
