# Generated by Django 3.2.7 on 2021-09-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
