# Generated by Django 3.2.7 on 2021-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_alter_quiz_passing_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
