# Generated by Django 3.2.7 on 2021-09-24 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_score_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passing_marks',
            field=models.IntegerField(default=1, help_text='Enter passing percentage', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
