# Generated by Django 3.2.7 on 2021-09-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_alter_quiz_passing_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
