# Generated by Django 3.2.7 on 2022-02-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0009_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileUpload',
        ),
    ]
